changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: New features
      labels:
        - enhancement
        - feature
    - title: Bug fixes
      labels:
        - bug
    - title: Security updates
      labels:
        - security
    - title: Documentation and experience
      labels:
        - documentation
    - title: Dependencies and maintenance
      labels:
        - dependencies
    - title: Other changes
      labels:
        - "*"
